name: Build and Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        dotnet-version: ['5.0', '6.0' ]

    steps:
    - uses: actions/checkout@v2
    - name: Setup .NET Core SDK ${{ matrix.dotnet-version }}
      uses: actions/setup-dotnet@v1.7.2
      with:
        dotnet-version: ${{ matrix.dotnet-version }}
    - name: Restore dependencies
      run: dotnet restore src/U8XmlParser/U8XmlParser.csproj
    - name: Build Debug
      run: dotnet build --no-restore -c Debug --framework net${{ matrix.dotnet-version }} src/U8XmlParser/U8XmlParser.csproj
    - name: Test Debug
      run: dotnet test --no-build --verbosity normal -c Debug --framework net${{ matrix.dotnet-version }} src/UnitTest/UnitTest.csproj
    - name: Build Release
      run: dotnet build --no-restore -c Release --framework net${{ matrix.dotnet-version }} src/U8XmlParser/U8XmlParser.csproj
    - name: Test Release
      run: dotnet test --no-build --verbosity normal -c Release --framework net${{ matrix.dotnet-version }} src/UnitTest/UnitTest.csproj
